baseURL: "https://jannik-roth.github.io/" 
title: Jannik P. Roth
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        # - name: Books
        #   url: books/
        #   weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        # - name: Courses
        #   url: courses/
        #   weight: 3
        # - name: Data
        #   url: data/
        #   weight: 4 
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 3

params:
    description: "This is the personal website of Jannik P. Roth."
    author: Jannik P. Roth
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    # MainSections: ["books","courses","papers","data"]
    MainSections: ["papers"] #,"blog"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jannik P. Roth
          subtitle: "I am a Doctoral Student at the University of Bonn, Germay. I hold a B.Sc. and M.Sc. Chemistry from the University of Bonn and University of Munich, respectively. My research focuses on the use of Artificial Intelligence in the field of Drug Development."
          imageUrl: "square.jpg"
          imageWidth: 240
          imageHeight: 240
          buttons:
            - name: Papers
              url: papers/
            # - name: Data
            #   url: data/
            # - name: Books
            #   url: books/
            # - name: Courses
            #   url: courses/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv_english.pdf
        - name: Email
          url: mailto:jproth@uni-bonn.de
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=kIkHxywAAAAJ
        - name: GitHub
          url: https://github.com/jannik-roth
        - name: LinkedIn
          url: https://www.linkedin.com/in/jannik-philipp-roth-372845332/
        - name: orcid
          url: https://orcid.org/0000-0001-6690-5601
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        # - name: Twitter
        #   url: https://x.com/pmichaillat
        # - name: Bluesky
        #   url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jannik P. Roth"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2